[package]
name = "bgfx"
version = "0.1.0"
authors = ["Johan Sköld <johan@skold.cc>"]

[dependencies]
bitflags = "0.8.2"
libc = "0.2.21"

[dependencies.bgfx-sys]
path = "bgfx-sys/"

[dev-dependencies]
cgmath = "0.14.0"
glutin = "0.7.4"
time = "0.1.36"
maplit = "*"
lazy_static = "*"